# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Setup flake8 annotations
      #uses: rbialon/flake8-annotations@v1
      uses: reviewdog/action-flake8@v3
    - name: Lint with flake8 
      id: autopep8
      uses: peter-evans/autopep8@v1
      with:
        args: -d --recursive .
      #run: |
        # stop the build if there are Python syntax errors or undefined names
        #flake8 . --count --max-complexity=10 --max-line-length=127 --statistics
    - name: Fail on exit autopep8
      if: steps.autopep8.outputs.exit-code == 2
      run: exit 1    
    - name: Test with pytest
      run: |
        python -m pytest tests
